services:
  stock-publisher:
    build: ./stock-publisher
    environment:
      RABBITMQ_URL: "amqp://stockmarket:supersecret123@rabbitmq:5672/"
    depends_on:
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # RabbitMQ Management Dashboard
    environment:
      RABBITMQ_DEFAULT_USER: "stockmarket"
      RABBITMQ_DEFAULT_PASS: "supersecret123"