services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # RabbitMQ Management Dashboard
    environment:
      RABBITMQ_DEFAULT_USER: "stockmarket"
      RABBITMQ_DEFAULT_PASS: "supersecret123"